# workflow syntax           https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# runs-on                   https://github.com/actions/virtual-environments
# setup-node@c4             https://github.com/actions/setup-node
# actions-yarn@v5.0.0       https://github.com/marketplace/actions/github-action-for-yarn
# FTP-Deploy-Action@v4.3.5  https://github.com/marketplace/actions/ftp-deploy

on:
  push:
    branches:
      - deploy
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - name: GIT checkout
      uses: actions/checkout@v4
    - name: Set Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: yarn install
      uses: borales/actions-yarn@v5.0.0
      with:
        cmd: install
    - name: 🔨 yarn build
      uses: borales/actions-yarn@v5.0.0
      with:
        cmd: build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        dry-run: false
        local-dir: dist/
        dangerous-clean-slate: true